#!/bin/bash -e

cd server/src/main
if go version; then
    echo "Compiling server..."
    go build -o buildshoot-server *.go

    mv buildshoot-server ../../../client
    cd ../../../client

    echo "Starting server..."
    ./buildshoot-server

    exit 0
else
    echo "ERROR: Go must be installed to compile the server."
    echo "Get it from http://www.golang.org"
    exit 1
fi

