#!/bin/bash -e

if go version; then
    export GOPATH="`pwd`/server"
    echo "Compiling server..."

    go get buildblast/server
    go build -o client/bin/server buildblast/server
    
    echo "Starting server..."
    client/bin/server

    exit 0
else
    echo "ERROR: Go must be installed to compile the server."
    echo "Get it from http://www.golang.org"
    exit 1
fi

