#!/bin/bash -e

if go version; then
	export GOPATH="`pwd`/../../"

	if [ ! -e "$GOPATH/src" ]; then
		echo "ERROR: Your git directory must be in a dir called src."
		echo "This means it should be src/buildblast/.git"
	fi

	export GOBIN="`pwd`/bin"
	echo "Compiling server..."
	mkdir -p "$GOBIN"
	go get buildblast/server

	cd client
	echo "Starting server..."
	../bin/server

	exit 0
else
	echo "ERROR: Go must be installed to compile the server."
	echo "Get it from http://www.golang.org"
	exit 1
fi
