#!/usr/bin/env python

import os
import re

includes = open('includes.js', 'w')
includes.write("""
// AUTOGENERATED, DO NOT EDIT
// Instead, run python genincludes.py to automatically
// regenerate the list (automatically including all
// JavaScript files in this directory and all
// subdirectories)

(function include(names) {
	for (var i = 0; i < names.length; i++) {
		var script = document.createElement('script');
		script.src = names[i];
		document.body.appendChild(script);
	}
}([
""")

for dirpath, dirnames, filenames in os.walk('.'):
	for filename in filenames:
		if not re.match(r'.+\.js$', filename):
			continue
		if re.match(r'^worker.js$', filename):
			continue
		if re.match(r'^includes.js$', filename):
			continue
		path = os.path.join('js/', dirpath, filename)
		includes.write("\t'{0}',\n".format(path))

includes.write("""]));
""")
