
// AUTOGENERATED, DO NOT EDIT
// Instead, run python genincludes.py to automatically
// regenerate the list (automatically including all
// JavaScript files in this directory and all
// subdirectories)

(function include(names) {
	for (var i = 0; i < names.length; i++) {
		var script = document.createElement('script');
		script.src = names[i];
		document.body.appendChild(script);
	}
}([
	'js/./settings.js',
	'js/./chunks/block.js',
	'js/./chunks/chunk.js',
	'js/./chunks/chunkManager.js',
	'js/./chunks/common.js',
	'js/./chunks/worker/chunkGeometry.js',
	'js/./chunks/worker/meshCommon.js',
	'js/./chunks/worker/noise.js',
	'js/./chunks/worker/workerChunkManager.js',
	'js/./chunks/worker/meshers/greedyMesher.js',
	'js/./chunks/worker/meshers/simpleMesher.js',
	'js/./chunks/worker/meshers/simpleNewMesher.js',
	'js/./entities/entityBar.js',
	'js/./entities/entityManager.js',
	'js/./entities/entityNetworkController.js',
	'js/./entities/entityPredictiveController.js',
	'js/./entities/historyBuffer.js',
	'js/./entities/playerEntity.js',
	'js/./geom/box.js',
	'js/./perf/chart.js',
	'js/./player/chat.js',
	'js/./player/controls.js',
	'js/./player/inventory.js',
	'js/./player/item.js',
	'js/./player/movement.js',
	'js/./player/playerUI.js',
	'js/./player/stack.js',
	'js/./shared/clock.js',
	'js/./shared/conn.js',
	'js/./shared/featureTester.js',
	'js/./shared/models.js',
	'js/./shared/world.js',
	'js/./tests/testCommon.js',
	'js/./tests/testMesh.js',
	'js/./tests/testSystem.js',
]));
