
// AUTOGENERATED, DO NOT EDIT
// Instead, run python genincludes.py to automatically
// regenerate the list (automatically including all
// JavaScript files in this directory and all
// subdirectories)

(function include(names) {
    for (var i = 0; i < names.length; i++) {
        var script = document.createElement('script');
        script.src = names[i];
        document.body.appendChild(script);
    }
}([
	'js/./1defaultSettings.js',
	'js/./1localSettings.js',
	'js/./box.js',
	'js/./chat.js',
	'js/./conn.js',
	'js/./featureTester.js',
	'js/./main.js',
	'js/./models.js',
	'js/./world.js',
	'js/./chunks/block.js',
	'js/./chunks/chunk.js',
	'js/./chunks/common.js',
	'js/./chunks/manager.js',
	'js/./chunks/worker/chunkGeometry.js',
	'js/./chunks/worker/noise.js',
	'js/./chunks/worker/threeVector.js',
	'js/./chunks/worker/twoVector.js',
	'js/./chunks/worker/workerChunkManager.js',
	'js/./chunks/worker/meshers/fastGreedyMesher.js',
	'js/./chunks/worker/meshers/greedyMesher.js',
	'js/./chunks/worker/meshers/meshCommon.js',
	'js/./chunks/worker/meshers/simpleFastMesher.js',
	'js/./chunks/worker/meshers/simpleGreedyMesher.js',
	'js/./chunks/worker/meshers/simpleMesher.js',
	'js/./entities/entity.js',
	'js/./entities/manager.js',
	'js/./loopHelpers/loop.js',
	'js/./perf/chart.js',
	'js/./player/clock.js',
	'js/./player/controls.js',
	'js/./player/inventory.js',
	'js/./player/items.js',
	'js/./player/player.js',
	'js/./player/playerPrediction.js',
	'js/./tests/chunkMeshing.js',
]));
