
// AUTOGENERATED, DO NOT EDIT
// Instead, run python genincludes.py to automatically
// regenerate the list (automatically including all
// JavaScript files in this directory and all
// subdirectories)

(function include(names) {
    for (var i = 0; i < names.length; i++) {
        var script = document.createElement('script');
        script.src = names[i];
        document.body.appendChild(script);
    }
}([
	'js/./featureTester.js',
	'js/./main.js',
	'js/./chat.js',
	'js/./models.js',
	'js/./conn.js',
	'js/./box.js',
	'js/./world.js',
	'js/./chunks/block.js',
	'js/./chunks/manager.js',
	'js/./chunks/noise.js',
	'js/./chunks/chunk.js',
	'js/./chunks/geometry.js',
	'js/./chunks/common.js',
	'js/./entities/manager.js',
	'js/./entities/entity.js',
	'js/./player/blastInventory.js',
	'js/./player/inventory.js',
	'js/./player/controls.js',
	'js/./player/playerPrediction.js',
	'js/./player/buildInventory.js',
	'js/./player/player.js',
]));
