development:
  adapter: postgresql
  encoding: unicode
  database: buildblast
  pool: 5
  username: buildblast
  password: rj8uoxIHqHFnnIzfXYFd5Q

test:
  adapter: postgresql
  encoding: unicode
  database: buildblast
  pool: 5
  username: buildblast
  password: rj8uoxIHqHFnnIzfXYFd5Q

production:
  adapter: postgresql
  encoding: unicode
  database: buildblast
  pool: 5
  username: buildblast
  password: rj8uoxIHqHFnnIzfXYFd5Q


